# Generated by Django 5.1.15 on 2026-04-25 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_slug', models.SlugField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'downloads_downloadjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
