# Generated by Django 5.1.15 on 2026-04-25 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_slug', models.SlugField(max_length=128, unique=True)),
                ('local_path', models.CharField(max_length=1024)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('downloading', 'Downloading'), ('ready', 'Ready'), ('failed', 'Failed')], default='downloading', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'models_registry_modelfile',
                'ordering': ['-created_at'],
            },
        ),
    ]
