# Generated by Django 5.1.15 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='mmproj_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
