# Generated by Django 5.1.15 on 2026-04-25 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('family', models.CharField(db_index=True, max_length=64)),
                ('source_url', models.URLField(max_length=500)),
                ('source_repo', models.CharField(max_length=200)),
                ('source_revision', models.CharField(max_length=64)),
                ('format', models.CharField(choices=[('gguf', 'Gguf'), ('safetensors', 'Safetensors'), ('awq', 'Awq'), ('gptq', 'Gptq')], max_length=16)),
                ('compatible_engines', models.JSONField(default=list)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('license_spdx', models.CharField(max_length=64)),
                ('license_url', models.URLField(blank=True, default='', max_length=500)),
                ('license_text_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('allowed_use', models.CharField(choices=[('commercial', 'Commercial'), ('research-only', 'Research Only'), ('restricted', 'Restricted')], max_length=32)),
                ('manifest_signature', models.CharField(max_length=200)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'catalog_model',
                'ordering': ['family', 'display_name'],
            },
        ),
    ]
