# Generated by Django 5.1.15 on 2026-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogmodel',
            options={'ordering': ['tier', 'family', 'display_name']},
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='successor_slug',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='tier',
            field=models.CharField(choices=[('tiny', 'Tiny — laptop CPU / edge (≤2B)'), ('small', 'Small — consumer GPU / Apple Silicon (3B–9B)'), ('medium', 'Medium — workstation GPU (12B–32B)'), ('large', 'Large — server / multi-GPU (70B+)'), ('coding', 'Coding specialist')], db_index=True, default='small', max_length=16),
        ),
    ]
