# Generated by Django 5.1.15 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogmodel_options_catalogmodel_deprecated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='mmproj_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='mmproj_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='mmproj_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='vision_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
