# Generated by Django 5.1.15 on 2026-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
