# Generated by Django 5.1.15 on 2026-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='system_prompt',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
